#+title: xerosere

This *xerosere* project extracts patterns initially developed in an ad-hoc way as
part of the [[https://github.com/brettviren/dune-xerosere][dune-xerosere]] development (see there for name origin) so that they
may be re-applied by others for other development efforts.  The patterns are
realized by the =xerosere= program.

The main aspects of a xerosere development environment:

- Allow scaling to a large number of source packages to be in scope for
  development while requiring much less than linear scaling of developer time
  and cognitive load.

- Leverage Spack (adding pixi/conda support is planned) to provide the
  dependencies that form the basis for building the code including use of
  additional Spack package repos.

- Support building and installing the developing source against multiple
  dependency bases by leveraging Spack (or pixi) environment views.

- Single-command global builds of all packages in development.  This includes
  CMake "super build" pattern (for now, only CMake-based source) and use of
  =spack develop=.

The xerosere project is also compatible with Spack/pixi interop via [[https://github.com/brettviren/spaxi][spaxi]].

* Install
#+begin_example
$ uv tool install git+https://github.com/brettviren/xerosere
#+end_example


* Quick start

#+begin_example

# Initialize green field
$ xerosere init workdir
$ cd workdir

# Install local spack and add some Spack package repos
$ xerosere extern bootstrap
$ xerosere extern repo git@github.com:WireCell/edep-simphony-spack.git
$ xerosere extern repo https://github.com/FNALssi/fnal_art.git
$ xerosere extern repo https://github.com/Framework-R-D/phlex-spack-recipes.git
$ xerosere extern repo git@github.com:WireCell/wire-cell-spack.git

# Make an initially empty (or primed) env
$ xerosere extern envs myenv [--from /path/to/env/spack.yaml]

$ t.b.d. commands to add packages, for now use bare spack

# Concretize the Spack graph and install its packages
$ xerosere spack concretize
$ xerosere spack install
#+end_example

See [[file:docs/walk-through.org]] for more ways to use this including leveraging a pre-existing Spack installation.

* Configuration

The =xerosere= program uses a chain of configuration sources to determine an
"active configuration".  The chain is first walked to construct one or more
possible, named configurations.  Any values with Python f-string syntax are
interpolated using other values in the parameter set and finally one parameter
set is chosen by name as specified by the parameter =config_name=.

The resolution phases follow a last-found-wins order:

1. built-in defaults (in ~xerosere.config.DEFAULTS~)
2. shell environment variables ~XEROSERE_<PARAM>~
3. XDG file ~~/.config/xerosere/config.toml~
4. local file ~<root>/.xerosere/config.toml~
5. explicit ~-c/--config <file>~
6. CLI option overrides ~--<param>~

Within the file layers, a special ~[env.DEFAULT]~ section provides the base
parameter set for every named ~[env.<name>]~ section.

Nomenclature: parameter ~foo_bar~ => env var ~XEROSERE_FOO_BAR~ => option
~--foo-bar~.

Relative path-valued parameters resolve against the *project root* which is the
nearest ancestor directory containing a ~.xerosere/~ sub-directory.

The =xerosere init= will prime the =.xerosere/= directory and =xerosere= commands will
record configuration to the local =.xerosere/config.toml= which may also be
modified by the user.

** CMake variables

Free-form CMake variable sets live in ~[cmake.<name>]~ tables.  An
~[env.<name>]~ section names one via ~cmake_config~ (configure step) and/or
~cmake_build~ (build step); each entry becomes a ~-D<key>=<value>~ passed to
cmake.  On the command line, ~xerosere dev config -D FOO=BAR~ passes through
extra defines; other trailing tokens that are not ~devel/~ package names are
passed verbatim to cmake.

* Welcome additions

- [ ] Use =mr= / MyRepos to simplify managing the many git clones involved.
- [ ] Making package-level dependency graphs (for now can directly use =cmake-examine= which is part of [[https://github.com/brettviren/tools][this tools collection]]).
- [ ] Commands to help manage envs: add packages, package grouping needed for complex builds (eg, with phlex involved)
- [ ] Defining xerosere envs from named (non-directory) Spack envs.
- [ ] Testing against Spack install areas in =/cvmfs=.
  
